apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - name: control
    port: 12865
    protocol: TCP
  - name: data0
    port: 35000
    protocol: TCP
  - name: python-http
    port: 8000
    protocol: TCP
  - name: fortio-http80
    port: 8080
    protocol: TCP
  - name: fortio-http79
    port: 8079
    protocol: TCP
  - name: fortio-http78
    port: 8078
    protocol: TCP
  selector:
    app: server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server-sa
      nodeSelector:
        role: server
      containers:
      - name: server
        image: stjinxuan.azurecr.io/ambient-performance
        imagePullPolicy: Always
        command: ["./server-and-sleep.sh"]
        ports:
        - containerPort: 12865
          name: control
        - containerPort: 6789
          name: echo
        - containerPort: 35000
          name: data0
        - containerPort: 8000
          name: python-http
        - containerPort: 8080
          name: fortio-http80
        - containerPort: 8079
          name: fortio-http79
        - containerPort: 8078
          name: fortio-http78
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        role: client
      containers:
      - name: client
        image: stjinxuan.azurecr.io/ambient-performance
        imagePullPolicy: Always
        command: ["/bin/sleep", "365d"]
