apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: istio
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: istio
spec:
  ports:
  - name: control
    port: 12865
    protocol: TCP
  - name: data0
    port: 35000
    protocol: TCP
  - name: data1
    port: 35001
    protocol: TCP
  - name: data2
    port: 35002
    protocol: TCP
  - name: data3
    port: 35003
    protocol: TCP
  - name: data4
    port: 35004
    protocol: TCP
  selector:
    app: server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        role: server
      containers:
      - name: server
        image: stjinxuan.azurecr.io/netperf
        imagePullPolicy: Never
        command: ["./server-and-sleep.sh"]
        ports:
        - containerPort: 12865
          name: control
        - containerPort: 35000
          name: data0
        - containerPort: 35001
          name: data1
        - containerPort: 35002
          name: data2
        - containerPort: 35003
          name: data3
        - containerPort: 35004
          name: data4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        role: client
      serviceAccountName: client
      containers:
      - name: client
        image: stjinxuan.azurecr.io/netperf
        imagePullPolicy: Never
        command: ["/bin/sleep", "365d"]
        args:
        - 365d
--- #-------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: direct
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: direct
spec:
  ports:
  - name: control
    port: 12865
    protocol: TCP
  - name: data0
    port: 35000
    protocol: TCP
  - name: data1
    port: 35001
    protocol: TCP
  - name: data2
    port: 35002
    protocol: TCP
  - name: data3
    port: 35003
    protocol: TCP
  - name: data4
    port: 35004
    protocol: TCP
  selector:
    app: server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: direct
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        role: server
      containers:
      - name: server
        image: stjinxuan.azurecr.io/netperf
        imagePullPolicy: Never
        command: ["./server-and-sleep.sh"]
        ports:
        - containerPort: 12865
          name: control
        - containerPort: 35000
          name: data0
        - containerPort: 35001
          name: data1
        - containerPort: 35002
          name: data2
        - containerPort: 35003
          name: data3
        - containerPort: 35004
          name: data4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: direct
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        role: client
      serviceAccountName: client
      containers:
      - name: client
        image: stjinxuan.azurecr.io/netperf
        imagePullPolicy: Never
        command: ["/bin/sleep", "365d"]
        args:
        - 365d
