# Configuration Set7: Latency Quantiles with telemetry v2 using NullVM with
# Stackdriver filter with metrics/logging/topology on.
telemetry_mode: "v2-stackdriver-nullvm"
conn:
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
qps:
  - 1000
duration: 240
metrics:
  - p50
  - p90
  - p99
perf_record: true
run_serversidecar: true
run_baseline: true