# Configuration Set10: CPU and memory with telemetryv2 using NullVM with
# Stackdriver filter with metrics/topology on.
telemetry_mode: "v2-stackdriver-nologging-nullvm"
conn:
  - 16
qps:
  - 10
  - 100
  - 500
  - 1000
  - 2000
  - 3000
duration: 240
metrics:
  - cpu
  - mem
perf_record: false
run_serversidecar: true
run_baseline: true