apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test-wasm-filter
spec:
  phase: STATS
  selector:
    matchLabels:
      app: wasm-test-server
  url: oci://gcr.io/istio-testing/wasm/header-injector:0.0.%PLACEHOLDER%
  imagePullPolicy: Always