apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: istio-prometheus
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'test'
    receivers:
      - name: 'test'
        webhook_configs:
          - url: 'http://am-webhook.istio-prometheus:5001/webhook'
        slack_configs:
          - api_url: "https://hooks.slack.com/services/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"
            channel: "#stability-test"
            send_resolved: true
            title: |-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove .GroupLabels.Names }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ with index .Alerts 0 -}}
                :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
                {{- if .Annotations.runbook }}   :notebook: *<{{ .Annotations.runbook }}|Runbook>*{{ end }}
              {{ end }}

              *Alert details*:

              {{ range .Alerts -}}
                *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
              *Description:* {{ .Annotations.description }}
              *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
type: Opaque
---
