apiVersion: v1
name: security tests
version: 1.0
description: Helm chart for sds citadel tests
keywords:
  - istio
  - citadel
  - sds
  - performance
  - qualification
sources:
  - http://github.com/istio/istio
engine: gotpl
