# Data: cpu/mem
# Filter: metadata-exchange and stackdriver filters and enable access log policy
# VM mode: nullvm
telemetry_mode: "v2-sd-full-nullvm-accesslog"
conn:
    - 16
qps:
    - 10
    - 100
    - 200
    - 400
    - 800
    - 1000
duration: 240
perf_record: true
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true

extra_labels: "mtls"

jitter: true
