apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: false
        stackdriver:
          enabled: true
          topology: true
          inboundAccessLogging: "FULL"
          outboundAccessLogging: "ERRORS_ONLY"
        accessLogPolicy:
          enabled: true
