apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasm-extensions-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasm-extensions-role
rules:
  - apiGroups: ["extensions.istio.io"]
    resources: ["wasmplugins"]
    verbs: ['*']
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/finalizers
      - replicasets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wasm-extensions-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wasm-extensions-role
subjects:
  - kind: ServiceAccount
    name: wasm-extensions-service-account
    namespace: {{ .Release.Namespace }}
---