---
apiVersion: v1
kind: Service
metadata:
  name: wasm-test-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: wasm-test-server
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: wasm-test-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-test-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: wasm-test-server
  template:
    metadata:
      labels:
        app: wasm-test-server
      annotations:
        proxy.istio.io/config: |-
          proxyMetadata:
            WASM_PURGE_INTERVAL: 1s
            WASM_MODULE_EXPIRY: {{.Values.moduleExpirySeconds}}s
    spec:
      containers:
      - image: {{ .Values.fortioImage }}
        imagePullPolicy: IfNotPresent
        name: wasm-test-server
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
