apiVersion: v1
kind: ServiceAccount
metadata:
  name: certmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: certmanager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanager-{{ .Values.namespace }}
  labels:
    app: certmanager
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "certificates/finalizers", "issuers", "clusterissuers", "orders", "orders/finalizers", "challenges"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "events", "services", "pods"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certmanager-{{ .Values.namespace }}
  labels:
    app: certmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certmanager-{{ .Values.namespace }}
subjects:
  - name: certmanager
    namespace: {{ .Values.namespace }}
    kind: ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: certmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certmanager
  template:
    metadata:
      labels:
        app: certmanager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: certmanager
      containers:
      - name: certmanager
        image: "{{ .Values.certManagerImage }}"
        imagePullPolicy: Always
        args:
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Values.namespace }}
  labels:
    app: certmanager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mailbox@{{ .Values.ingressDomain }}
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.namespace }}
  labels:
    app: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mailbox@{{ .Values.ingressDomain }}
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-staging
  namespace: {{ .Values.namespace }}
spec:
  secretName: cert-staging-tls
  # A newly issued "Let's Encrypt" cert is valid for 90 days since 1 hour ago.
  # The following directive will trigger renewal every 30 mins.
  renewBefore: 129510m # (90 days) minus (1 hour) minus (30 mins)
  issuerRef:
    name: letsencrypt-staging
  commonName: {{ .Values.ingressDomain }}
  dnsNames:
  - {{ .Values.ingressDomain }}
  acme:
    config:
    - http01:
        ingressClass: istio-ingress-{{ .Values.namespace }}
      domains:
      - {{ .Values.ingressDomain }}
