apiVersion: v1
data:
  mesh: |
    accessLogEncoding: TEXT
    accessLogFile: /dev/null
    accessLogFormat: ''
    configSources:
    - address: istio-galley.istio-system.svc:9901
      tlsSettings:
        mode: ISTIO_MUTUAL
    connectTimeout: 10s
    defaultConfig:
      binaryPath: /usr/local/bin/envoy
      concurrency: 2
      configPath: /etc/istio/proxy
      connectTimeout: 10s
      controlPlaneAuthPolicy: MUTUAL_TLS
      discoveryAddress: istio-pilot.istio-system:15011
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      proxyAdminPort: 15000
      serviceCluster: istio-proxy
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    disablePolicyChecks: true
    dnsRefreshRate: 300s
    enableSdsTokenMount: false
    enableTracing: true
    ingressService: istio-ingressgateway
    localityLbSetting: {}
    mixerCheckServer: istio-telemetry.istio-system.svc.cluster.local:9091
    mixerReportServer: istio-telemetry.istio-system.svc.cluster.local:9091
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    policyCheckFailOpen: false
    rootNamespace: istio-system
    sdsUdsPath: null
    sdsUseK8sSaJwt: false
    trustDomain: null
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: istio
    chart: istio
    heritage: Tiller
    release: istio
  name: istio
  namespace: istio-system
