apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: true
        prometheus:
          enabled: true
          wasmEnabled: true
        stackdriver:
          enabled: false
