apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"ssd"},"parameters":{"type":"pd-ssd"},"provisioner":"kubernetes.io/gce-pd"}
  creationTimestamp: null
  name: ssd
  selfLink: /apis/storage.k8s.io/v1/storageclasses/ssd
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
