apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
        stackdriver:
          enabled: true
          topology:
            enabled: true
          logging:
            enabled: true
      v1:
        enabled: false