apiVersion: apps/v1
kind: Deployment
metadata:
  name: http10-client
spec:
  selector:
    matchLabels:
      app: http10-client
  template:
    metadata:
      annotations:
        HTTP10: "1"
      labels:
        app: http10-client
    spec:
      containers:
        - name: http10-client
          image: {{ .Values.curlImage }}
          args:
            - bash
            - -c
            - |-
              while true; do
                curl -sS  -o /dev/null -w "%{http_code}\n" fortio-server:8080/echo --http1.0
                sleep .1
              done
          resources:
            requests:
              cpu: 100m
              memory: 128Mi