# Values for setting replicas and resources high, to handle large clusters
global:
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi

gateways:
  istio-ingressgateway:
    replicas: 3
    autoscaleMin: 3
    autoscaleMax: 5
    resources:
      limits:
        cpu: 6000m
        memory: 512Mi
      requests:
        cpu: 4000m
        memory: 512Mi

pilot:
  replicaCount: 2
  autoscaleMax: 10
  resources:
    requests:
      cpu: 4800m
      memory: 2G
    limits:
      cpu: 5800m
      memory: 12G

mixer:
  resources:
    requests:
      cpu: 3800m
      memory: 4G
    limits:
      cpu: 5800m
      memory: 5G
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 15