apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    nodeAgent:
      enabled: false

  values:
    global:
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: true
      sds:
        enabled: false
        udsPath: ""
        useNormalJwt: false
    gateways:
      istio-ingressgateway:
        sds:
          enabled: false
    security:
      # Short lived cert to test rotation.
      workloadCertTtl: 300m