apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            maxReplicas: 5
            minReplicas: 3
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
          resources:
            limits:
              cpu: 4800m
              memory: 1G
            requests:
              cpu: 1000m
              memory: 512Mi
    pilot:
      enabled: true
      k8s:
        resources:
          limits:
            cpu: 4800m
            memory: 6G
          requests:
            cpu: 1000m
            memory: 2G
  values:
    global:
      proxy:
        enableCoreDump: true
        resources:
          requests:
            cpu: 250m
            memory: 256Mi


