# ASM specific overlay files which enable stats filters and other necessary override.
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    telemetry:
      v2:
        prometheus:
          enabled: true
    global:
      proxy:
        # tracing may not work for old asm release before 1.6
        tracer: stackdriver
        accessLogFile: "/dev/stdout"