apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    citadel:
      k8s:
        replicaCount: 3
    nodeAgent:
      enabled: false

  values:
    global:
      mtls:
        enabled: true
      sds:
        enabled: false
        udsPath: ""
        useNormalJwt: false
    security:
      workloadCertTtl: 30m
    gateways:
      istio-ingressgateway:
        sds:
          enabled: false