// Code generated by protoc-gen-alias. DO NOT EDIT.
package v1alpha

import "istio.io/tools/cmd/protoc-gen-alias/test/v1"

type Simple = v1.Simple
type Simple_Name = v1.Simple_Name
type Simple_Number = v1.Simple_Number
type SimpleWithMap = v1.SimpleWithMap
type SimpleWithMap_Nested = v1.SimpleWithMap_Nested
type ReferencedMap = v1.ReferencedMap
type ImportedReference = v1.ImportedReference
