apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-client
spec:
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
      # We sleep first and will execute mysql cli later. This ensures the cli command will
      # send traffic to mysql server after iptable sidecar traffic injection finishes.
      - args:
        - bash
        - -c
        - |-
          sleep 3
          for i in `seq 1 1000`; do
            echo "Attempt to connect to server, $i"
            mysql -uroot -proot -h mysql-server  -P3306  --connect-timeout -e 'show databases;'
            sleep 1
          done
        image: mysql
        imagePullPolicy: IfNotPresent
        name: mysql-client
  