apiVersion: v1
kind: Service
metadata:
  name: srv-default
spec:
  ports:
  - port: 8080
    name: http-echo
  - port: 8079
    name: grpc-ping
  selector:
    app: srv-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: srv-default
  template:
    metadata:
      labels:
        app: srv-default
    spec:
      containers:
      - name: fortio-server
        image: {{ .Values.fortioImage }}
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
         - containerPort: 8079
        args:
          - server
        resources:
          requests:
            cpu: 250m
            memory: 256m
