apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    telemetry:
      enabled: false
  values:
    telemetry:
      enabled: true
      v2:
        enabled: true
      v1:
        enabled: false