// Copyright 2019 Istio Authors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

package scanner

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/pflag"
	"k8s.io/apimachinery/pkg/runtime/schema"
	gengo "k8s.io/gengo/v2"
	"k8s.io/gengo/v2/codetags"
	"k8s.io/gengo/v2/generator"
	"k8s.io/gengo/v2/types"
	"k8s.io/klog/v2"

	"istio.io/tools/cmd/kubetype-gen/generators"
	"istio.io/tools/cmd/kubetype-gen/metadata"
)

const (
	// enabledTagName is the root tag used to identify types that need a corresponding kube type generated
	enabledTagName = "kubetype-gen"

	// groupVersionTagName is the tag used to identify the k8s group/version associated with the generated types.
	groupVersionTagName = enabledTagName + ":groupVersion"

	// kubeTypeTagName is used to identify the name(s) of the types to be generated from the type with this tag.
	// If this tag is not present, the k8s type will have the same name as the source type.  If this tag is specified
	// multiple times, a k8s type will be generated for each value.
	kubeTypeTagName = enabledTagName + ":kubeType"

	// kubeTagsTagTemplate is used to identify a comment tag that should be added to the generated kubeType.  This
	// allows different sets of tags to be used when a single type is the source for multiple kube types (e.g. where one
	// is namespaced and another is not).  The tag should not be prefixed with '+', as this will be added by the
	// generator.  This may be specified multiple times, once for each tag to be added to the generated type.
	kubeTagsTagTemplate = enabledTagName + ":%s:tag"
)

// Scanner is used to scan input packages for types with kubetype-gen tags
type Scanner struct {
	outputPackage  string
	outputBase     string
	goHeaderFile   string
	trimPathPrefix string
}

// AddFlags registers the scanner's CLI flags on the given FlagSet.
func (s *Scanner) AddFlags(fs *pflag.FlagSet) {
	fs.StringVarP(&s.outputPackage, "output-package", "p", "", "The output package import path for generated types")
	fs.StringVarP(&s.goHeaderFile, "go-header-file", "h", "", "File containing boilerplate header text for generated files")
	fs.StringVarP(&s.outputBase, "output-base", "o", defaultSourceTree(), "Base directory for output (defaults to first GOPATH entry/src)")
	fs.StringVar(&s.trimPathPrefix, "trim-path-prefix", "", "If set, trim this prefix from --output-package when writing files")
}

func defaultSourceTree() string {
	if gopath := os.Getenv("GOPATH"); gopath != "" {
		return filepath.Join(filepath.SplitList(gopath)[0], "src")
	}
	return "."
}

// Targets scans input packages for types with kubetype-gen tags and returns generator targets.
func (s *Scanner) Targets(c *generator.Context) []generator.Target {
	// Do NOT pass StdBuildTag here. Downstream generators (deepcopy-gen, client-gen) use
	// the "ignore_autogenerated" build tag when loading input packages to skip already-generated
	// files. If kubetype-gen's output carries //go:build !ignore_autogenerated, those files
	// are excluded and the downstream generators see an empty package.
	boilerplate, err := gengo.GoBoilerplate(s.goHeaderFile, "", "// Code generated by kubetype-gen. DO NOT EDIT.")
	if err != nil {
		klog.Fatalf("Failed loading boilerplate: %v", err)
	}

	metadataStore := metadata.NewMetadataStore(s.getBaseOutputPackage(c), &c.Universe, s.outputBase, s.trimPathPrefix)
	fail := false

	klog.V(5).Info("Scanning input packages")
	for _, input := range c.Inputs {
		klog.V(5).Infof("Scanning package %s", input)
		pkg := c.Universe[input]
		if pkg == nil {
			klog.Warningf("Package not found: %s", input)
			continue
		}
		if strings.HasPrefix(s.outputPackage, pkg.Path) {
			klog.Warningf("Ignoring package %s as it is located in the output package %s", pkg.Path, s.outputPackage)
			continue
		}

		pkgTags := codetags.Extract("+", pkg.DocComments)

		defaultGV, err := getGroupVersion(pkgTags, nil)
		if err != nil {
			klog.Errorf("Could not calculate Group/Version for package %s: %v", pkg.Path, err)
			fail = true
		} else if defaultGV != nil {
			if len(defaultGV.Group) == 0 {
				klog.Errorf("Invalid Group/Version for package %s, Group not specified for Group/Version: %v", pkg.Path, defaultGV)
				fail = true
			} else {
				klog.V(5).Infof("Default Group/Version for package: %s", defaultGV)
			}
		}

		for _, t := range pkg.Types {
			comments := make([]string, 0, len(t.CommentLines)+len(t.SecondClosestCommentLines))
			comments = append(comments, t.CommentLines...)
			comments = append(comments, t.SecondClosestCommentLines...)
			typeTags := codetags.Extract("+", comments)
			if _, exists := typeTags[enabledTagName]; exists {
				var gv *schema.GroupVersion
				gv, err = getGroupVersion(typeTags, defaultGV)
				if err != nil {
					klog.Errorf("Could not calculate Group/Version for type %s: %v", t, err)
					fail = true
					continue
				} else if gv == nil || len(gv.Group) == 0 {
					klog.Errorf("Invalid Group/Version for type %s: %s", t, gv)
					fail = true
					continue
				}
				versions := extractVersions(comments)
				if len(versions) == 0 {
					// Types without +cue-gen versions tags use the version from groupVersion.
					versions = []string{gv.Version}
				}
				for _, v := range versions {
					gv := *gv
					gv.Version = v
					packageMetadata := metadataStore.MetadataForGV(&gv)
					if packageMetadata == nil {
						klog.Errorf("Could not create metadata for type: %s", t)
						fail = true
						continue
					}

					kubeTypes := createKubeTypesForType(c, t, packageMetadata.TargetPackage())
					klog.V(5).Infof("Kube types %v will be generated with Group/Version %s, for raw type in %s", kubeTypes, gv, t)
					err = packageMetadata.AddMetadataForType(t, kubeTypes...)
					if err != nil {
						klog.Errorf("Error adding metadata source for %s: %v", t, err)
						fail = true
					}
				}
			}
		}
	}

	klog.V(5).Info("Finished scanning input packages")

	validationErrors := metadataStore.Validate()
	if len(validationErrors) > 0 {
		for _, validationErr := range validationErrors {
			klog.Error(validationErr)
		}
		fail = true
	}
	if fail {
		klog.Exit("Errors occurred while scanning input.  See previous output for details.")
	}

	var targets []generator.Target
	for _, source := range metadataStore.AllMetadata() {
		if len(source.RawTypes()) == 0 {
			klog.Warningf("Skipping generation of %s, no types to generate", source.GroupVersion())
			continue
		}
		klog.V(2).Infof("Adding package generator for %s.", source.GroupVersion())
		targets = append(targets, generators.NewPackageGenerator(source, boilerplate))
	}
	return targets
}

func (s *Scanner) getBaseOutputPackage(c *generator.Context) *types.Package {
	return c.Universe.Package(s.outputPackage)
}

func extractVersions(comments []string) []string {
	var versions []string
	for _, line := range comments {
		// Looking for something like '+cue-gen:Simple:versions:v1,v1alpha'
		if strings.HasPrefix(line, "+cue-gen:") {
			items := strings.Split(line, ":")
			if len(items) != 4 {
				continue
			}
			if items[2] == "versions" {
				versions = append(versions, strings.Split(items[3], ",")...)
			}
		}
	}
	return versions
}

func getGroupVersion(tags map[string][]string, defaultGV *schema.GroupVersion) (*schema.GroupVersion, error) {
	if values := tagValues(tags, groupVersionTagName); len(values) > 0 {
		gv, err := schema.ParseGroupVersion(values[0])
		if err == nil {
			return &gv, nil
		}
		return nil, fmt.Errorf("invalid group version '%s' specified: %v", values[0], err)
	}
	return defaultGV, nil
}

// tagValues extracts values from gengo/v2 codetag lines. Unlike gengo v1, v2 stores
// the full tag line after '+' (e.g. "kubetype-gen:groupVersion=extensions.istio.io/v1alpha1")
// rather than just the value portion.
func tagValues(tags map[string][]string, tagName string) []string {
	raw, exists := tags[tagName]
	if !exists {
		return nil
	}
	values := make([]string, 0, len(raw))
	prefix := tagName + "="
	for _, line := range raw {
		if strings.HasPrefix(line, prefix) {
			values = append(values, line[len(prefix):])
			continue
		}
		if line == tagName {
			continue
		}
		if idx := strings.Index(line, "="); idx >= 0 {
			values = append(values, line[idx+1:])
			continue
		}
		values = append(values, line)
	}
	return values
}

func createKubeTypesForType(c *generator.Context, t *types.Type, outputPackage *types.Package) []metadata.KubeType {
	namesForType := kubeTypeNamesForType(t)
	newKubeTypes := make([]metadata.KubeType, 0, len(namesForType))
	for _, name := range namesForType {
		tags := getTagsForKubeType(t, name)
		newKubeTypes = append(newKubeTypes, metadata.NewKubeType(t, c.Universe.Type(types.Name{Name: name, Package: outputPackage.Path}), tags))
	}
	return newKubeTypes
}

func kubeTypeNamesForType(t *types.Type) []string {
	names := []string{}
	comments := make([]string, 0, len(t.CommentLines)+len(t.SecondClosestCommentLines))
	comments = append(comments, t.CommentLines...)
	comments = append(comments, t.SecondClosestCommentLines...)
	tags := codetags.Extract("+", comments)
	if values := tagValues(tags, kubeTypeTagName); len(values) > 0 {
		for _, name := range values {
			if len(name) > 0 {
				names = append(names, name)
			}
		}
		if len(names) == 0 {
			klog.Errorf("Invalid value specified for +%s in type %s.  Using default name %s.", kubeTypeTagName, t, t.Name.Name)
			names = append(names, t.Name.Name)
		}
	} else {
		names = append(names, t.Name.Name)
	}
	return names
}

func getTagsForKubeType(t *types.Type, name string) []string {
	tagName := fmt.Sprintf(kubeTagsTagTemplate, name)
	comments := make([]string, 0, len(t.CommentLines)+len(t.SecondClosestCommentLines))
	comments = append(comments, t.CommentLines...)
	comments = append(comments, t.SecondClosestCommentLines...)
	tags := codetags.Extract("+", comments)
	return tagValues(tags, tagName)
}
