# Configuration Set4: Latency Quantiles with mixer disabled
mixer_mode: "nomixer"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
qps:
    - 1000
duration: 240
size: 1024
metrics:
    - p50
    - p90
    - p99
perf_record: true
run_serversidecar: true
run_baseline: true
