apiVersion: v1
kind: Service
metadata:
  name: srv-locality-distribute
spec:
  ports:
  - port: 8080
    name: http-echo
  - port: 8079
    name: grpc-ping
  selector:
    app: srv-locality-distribute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-locality-distribute
spec:
  replicas: 4
  selector:
    matchLabels:
      app: srv-locality-distribute
  template:
    metadata:
      labels:
        app: srv-locality-distribute
    spec:
      containers:
      - name: fortio-server
        image: fortio/fortio:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
         - containerPort: 8079
        args:
          - server
        resources:
          requests:
            cpu: 250m
            memory: 256m
---
apiVersion: v1
kind: Service
metadata:
  name: cli-locality-distribute
spec:
  ports:
  - port: 8080
    name: http-echo
  selector:
    app: cli-locality-distribute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-locality-distribute
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cli-locality-distribute
  template:
    metadata:
      labels:
        app: cli-locality-distribute
    spec:
      containers:
      - name: fortio-client
        image: fortio/fortio:latest
        imagePullPolicy: Always
        args:
        - load
        - -t
        - 0
        - -abort-on
        - -1
        - -allow-initial-errors
        - -c
        - 10
        - -qps
        - 100
        - http://srv-locality-distribute:8080/debug
        resources:
          requests:
            cpu: 250m
            memory: 256m
