global:
  controlPlaneSecurityEnabled: true

  mtls:
    enabled: true
  disablePolicyChecks: true

  sidecarInjectorWebhook:
    enabled: true
    rewriteAppHTTPProbe: true

mixer:
  policy:
    enabled: false

  telemetry:
    enabled: true
 
grafana:
  enabled: true

tracing:
  enabled: true
