# Fortio with 0.8.0 sidecar
apiVersion: v1
kind: Service
metadata:
  name: fortio080
spec:
  ports:
  - port: 8080
    name: http-echo
  - port: 8079
    name: grpc-ping
  selector:
    app: fortiov080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortiov080
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortiov080
        version: fortio080
      annotations:
        sidecar.istio.io/proxyImage: istio/proxyv2:0.8.0
    spec:
      containers:
      - name: echosrv
        image: {{ .Values.fortioImage }}
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
         - containerPort: 8079
        args:
          - server
        resources:
          requests:
            cpu: 800m
            memory: "1G"
          limits:
            cpu: 1000m
            memory: "1G"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fortio080
spec:
  hosts:
  - "fortio080.{{.Values.domain}}"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: fortio080.test.svc.cluster.local
        port:
          number: 8080
