
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: secured-ingress
#  annotations:
#    kubernetes.io/ingress.class: istio
#spec:
#  tls:
#    - secretName: istio-ingress-certs
#  rules:
#  - http:
#      paths:
#      - path: /http
#        backend:
#          serviceName: a
#          servicePort: 80
#      - path: /pasta
#        backend:
#          serviceName: b
#          servicePort: 8080
#      - path: /.*
#        backend:
#          serviceName: a
#          servicePort: 7070
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: merge-foo1
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: fortio.{{ .Values.domain }}
    http:
      paths:
      - path: /lucky2
        backend:
          serviceName: a
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: regular-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: httpbin.{{ .Values.domain }}
    http:
      paths:
      - path: /lucky1
        backend:
          serviceName: c
          servicePort: 8080
      - path: /b.*
        backend:
          serviceName: b
          servicePort: 80
      - path: /.well_known/foo
        backend:
            serviceName: a
            servicePort: 80
      - path: /io.grpc/method
        backend:
            serviceName: a
            servicePort: 80
      - path: /c
        backend:
          serviceName: c
          servicePort: 80
      - path: /.*
        backend:
          serviceName: httpbin
          servicePort: 8000
  - host: fortiotls.{{ .Values.domain }}
    http:
      paths:
      - path: /foo
        backend:
          serviceName: a
          servicePort: 8080
