apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  - port: 9085
    targetPort: 9085
    name: tcp
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: golang:1.12.5
        args:
        - go
        - run
        - /script/main.go
        ports:
        - containerPort: 8085
          name: http-85
        - containerPort: 9085
          name: tcp-85
        - containerPort: 8087
          name: http-87
        - containerPort: 9087
          name: tcp-87
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - name: program-volume
          mountPath: /script
      volumes:
        - name: program-volume
          configMap:
            name: script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  main.go: |-
{{ .Files.Get "main.go" | indent 4 }}
---