apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: {{ .Values.fortioImage }}
        args:
        - load
        - -qps
        - "{{ .Values.qps }}"
        - -t
        - "0"
        - http://httpbin:8080/200 # /200 to httpbin results in a 404.
                                  # The intermediary will prepend /status to it.
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
