## Fortio clients generating traffic on different components.
# Generally use the ingress gateway - to capture non-istio service as well.
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortio-cli-raw
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: fortio-cli-raw
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: echosrv
        image: istio/fortio:latest
        imagePullPolicy: Always
        args:
          - load
          - -t
          - "0"
          - -c
          - "32"
          - -qps
          - "{{ .Values.qps }}"
          - -H
          - "Host: fortionoistio.{{ .Values.domain }}"
          - "http://{{ .Values.ingress }}/echo?size=5000"
        resources:
          requests:
            cpu: 800m
            memory: "1G"
          limits:
            cpu: 1000m
            memory: "1G"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortio-cli-notls
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: fortio-cli1
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: echosrv
        image: istio/fortio:latest
        imagePullPolicy: Always
        args:
          - load
          - -t
          - "0"
          - -c
          - "32"
          - -qps
          - "{{ .Values.qps }}"
          - -H
          - "Host: fortiomaster.{{ .Values.domain }}"
          - "http://{{ .Values.ingress }}/echo?size=5000"
        resources:
          requests:
            cpu: 800m
            memory: "1G"
          limits:
            cpu: 1000m
            memory: "1G"
---
