---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fortio-headless
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fortio-headless
    spec:
      containers:
      - name: echosrv
        image: {{ .Values.fortioImage }}
        ports:
         - containerPort: 8080
         - containerPort: 8079
        args:
          - server
---
# Headless version
apiVersion: v1
kind: Service
metadata:
  name: fortio-headless
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http-echo
  - port: 8079
    name: grpc-ping
  selector:
    app: fortio-headless
