# Gateway config, and associated virtual services

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
{{- if $.Values.certManager }}
  - port:
      number: 443
      name: https-default
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
{{- end }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "pilot.{{ .Values.domain }}"
    - "fortio.{{ .Values.domain }}"
    - "fortio2.{{ .Values.domain }}"
    - "fortiotls.{{ .Values.domain }}"
    - "fortiottls.{{ .Values.domain }}"
    - "fortionoistio.{{ .Values.domain }}"
    - "fortionoistio1.{{ .Values.domain }}"
    - "bookinfo.{{ .Values.domain }}"
    - "httpbin.{{ .Values.domain }}"
    - "fortio080.{{ .Values.domain }}"
    - "fortio10rc1.{{ .Values.domain }}"
    - "fortiomaster.{{ .Values.domain }}"
    - "fortiocli.{{ .Values.domain }}"
    - "fortio-tproxy.{{ .Values.domain }}"
  - port:
      number: 5201
      protocol: TCP
      name: tcp-iperf3
    hosts:
    - "*"
  - port:
      number: 5202
      protocol: TCP
      name: tcp-iperf3-noistio
    hosts:
    - "*"
  - port:
      number: 5203
      protocol: TCP
      name: tcp-iperf-tls
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pilot
spec:
  hosts:
  - "pilot.{{ .Values.domain }}"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: istio-pilot.istio-system.svc.cluster.local
        port:
          number: 9093

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.{{ .Values.domain }}"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: productpage.bookinfo.svc.cluster.local
        port:
          number: 9080

---
