
#apiVersion: networking.istio.io/v1alpha3
#kind: Gateway
#metadata:
#  name: istio-iperf-gateway
#spec:
#  selector:
#    istio: ingressgateway
#  servers:
#  - port:
#      number: 5203
#      protocol: TCP
#      name: tcp-iperf-tls
#    hosts:
#    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iperf-tls
spec:
  hosts:
  - "iperf-tls.{{ .Values.domain }}"
  gateways:
  - istio-gateway
  tcp:
  - match:
    - port: 5203
    route:
    - destination:
        host: iperf3-tls.test.svc.cluster.local
        port:
          number: 5203
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-tls
spec:
  ports:
  - name: tcp
    port: 5203
    targetPort: 5203
  selector:
    app: iperf3-tls
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: iperf3-tls
spec:
  peers:
  - mtls: {}
  peer_is_optional: true
  targets:
  # Must be short name of service
  - name: iperf3-tls
    # subsets: "v2"
    ports:
    # name also supported
    # TODO: this should be target port (container)
    - number: 5203
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: iperf3tls
spec:
  host:  iperf3-tls.test.svc.cluster.local
  trafficPolicy:
    tls:
      # Equivalent with ISTIO_MUTUAL
      mode: MUTUAL
      client_certificate: /etc/certs/cert-chain.pem
      private_key: /etc/certs/key.pem
      ca_certificates: /etc/certs/root-cert.pem
      subject_alt_names:
      - spiffe://cluster.local/ns/test/sa/default


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iperf3-tls
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf3-tls
    spec:
      containers:
      - image: docker.io/networkstatic/iperf3
        imagePullPolicy: IfNotPresent
        name: iperf3
        ports:
        - containerPort: 5203
        args:
        - '-s'
        - '-p'
        - '5203'
        resources:
          requests:
            cpu: 1000m
            memory: "1G"
          limits:
            cpu: 1000m
            memory: "2G"
