# Data: latency
# Config: security_authz_path
# VM mode: nullvm
telemetry_mode: "none"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
qps:
    - 1000
duration: 240
perf_record: true
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

extra_labels: "security_authz_path"

jitter: true
